EMULATOR_ADDITIONAL_ARGS: null
EMULATOR_ANDROID_VERSION: '13.0'
EMULATOR_CONFIG_PATH: null
EMULATOR_DATA_PARTITION: null
EMULATOR_DEVICE: Samsung Galaxy S10
EMULATOR_IMG_TYPE: google_apis_playstore
EMULATOR_NAME: null
EMULATOR_NO_SKIN: null
EMULATOR_SYS_IMG: x86_64
